
from app.kernel import kernel

result = kernel.run(
    "github.modify_file",
    owner="RyGuyR6",
    repo="odin-test",
    path="README.md",
    content="""# Odin Kernel

The Kernel executed this workflow successfully.
""",
    commit_message="Kernel execution test",
    pr_title="Kernel Execution Test",
    pr_body="Generated by the Odin Kernel.",
)

print()

print("=" * 60)
print("KERNEL RESULT")
print("=" * 60)

print(result)
